language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to run tests
install:
  - pip install codecov
script:
  - coverage run --source=. -m unittest discover
after_success:
  - codecov